x-superset-image: &superset-image superset-keycloak:dev
x-superset-depends-on:
  &superset-depends-on
  - redis
x-superset-volumes:
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  &superset-volumes
  - ./docker:/app/docker
  - ./superset/static:/app/superset/static
  - superset_home:/app/superset_home

x-superset-environment:
  &superset-environment
  - FLASK_ENV=development
  - SUPERSET_ENV=development
  - SUPERSET_LOAD_EXAMPLES=yes

version: "3.7"

volumes:
  redis:
    external: false
  superset_home:
    external: false

services:
  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  superset-app:
    env_file: .env
    image: *superset-image
    build:
      context: .
      dockerfile: Dockerfile.back
    command: [ "/app/docker/docker-bootstrap.sh", "app-gunicorn" ]
    user: "root"
    ports:
      - $HOST_PORT:$SUPERSET_PORT
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    environment: *superset-environment
      

  superset-frontend:
    env_file: .env
    image: superset-front
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: superset_frontend
    user: "root"
    volumes:
      - ./superset/:/app/superset/
      - ./superset-frontend/src:/app/superset-frontend/src

  superset-init:
    image: *superset-image
    build:
      context: .
      dockerfile: Dockerfile.back
    command: [ "/app/docker/docker-init.sh" ]
    env_file: .env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    environment: *superset-environment

  superset-worker:
    image: *superset-image
    build:
      context: .
      dockerfile: Dockerfile.back
    command: [ "/app/docker/docker-bootstrap.sh", "worker" ]
    env_file: .env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    environment: *superset-environment

  superset-worker-beat:
    image: *superset-image
    build:
      context: .
      dockerfile: Dockerfile.back
    command: [ "/app/docker/docker-bootstrap.sh", "beat" ]
    env_file: .env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    environment: *superset-environment
